### ISSUE TITLE
Summary of machine learning libraries

### ISSUE THREAD

**Issue by gmrukwa** [spectre-team/spectre#41]
The task is to prepare an **article in wiki**, which explains pros and cons of different machine learning libraries for C++ or .NET.

Important aspects are:

* documentation
* support
* community
* coverage of our needs
* integration with our data structures and standard C++ / .NET structures

Please remember, that some algorithms will be implemented by us regardless their availability in those libs.

**Comment by gmrukwa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Summary of machine learning libraries](https://trello.com/c/QYqd2i3p/55-summary-of-machine-learning-libraries)

**Comment by Regis128** [comment]
https://github.com/spectre-team/spectre/wiki/machine_learning_library

**Comment by gmrukwa** [comment]
So far so good. I think we'll use couple of them to cover our needs.
