### ISSUE TITLE
Summary of statistical libraries

### ISSUE THREAD

**Issue by gmrukwa** [spectre-team/spectre#42]
The task is to prepare an **article in wiki**, which explains pros and cons of different statistical libraries for C++ or .NET.

Important aspects are:

* documentation
* support
* community
* coverage of our needs
* integration with our data structures and standard C++ / .NET structures

**Comment by gmrukwa** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Summary of statistical libraries](https://trello.com/c/TP2adVpb/56-summary-of-statistical-libraries)

**Comment by gmrukwa** [comment]
https://github.com/spectre-team/spectre/wiki/statistic-library

**Comment by Regis128** [comment]
https://github.com/spectre-team/spectre/wiki/machine_learning_library

**Comment by gmrukwa** [comment]
To sum up: it seems like **R** is the best we can get.
